version: "3.8"
services:
  db:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: "${pg_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${pg_db}"
    ports:
      - 5432:5432
    volumes:
      - ./pg_db:/var/lib/postgresql
  adminer:
    image: adminer
    container_name: adminer_containerr
    restart: always
    ports:
      - 8081:8080
volumes:
  pg_db: